// Poppy Compiler - Auto-Generated Label Unit Tests
// Copyright © 2026

using Poppy.Core.Lexer;
using Poppy.Core.Parser;
using Poppy.Core.Semantics;

namespace Poppy.Tests.Semantics;

/// <summary>
/// Tests for auto-generating labels from JSR/JMP targets.
/// </summary>
public sealed class AutoGeneratedLabelTests {
	/// <summary>
	/// Helper to parse and analyze source code with auto-label generation.
	/// </summary>
	private static SemanticAnalyzer AnalyzeWithAutoLabels(string source, bool enableAutoLabels = true) {
		var lexer = new Poppy.Core.Lexer.Lexer(source, "test.pasm");
		var tokens = lexer.Tokenize();
		var parser = new Poppy.Core.Parser.Parser(tokens);
		var program = parser.Parse();

		var analyzer = new SemanticAnalyzer(TargetArchitecture.MOS6502);
		analyzer.AutoGenerateRoutineLabels = enableAutoLabels;
		analyzer.Analyze(program);
		return analyzer;
	}

	[Fact]
	public void AutoGenerateLabels_JsrTarget_CreatesSubLabel() {
		var source = @"
            .org $8000
            jsr $8100
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("sub_8100"));
		Assert.Equal(0x8100, analyzer.SymbolTable.Symbols["sub_8100"].Value);
	}

	[Fact]
	public void AutoGenerateLabels_JmpTarget_CreatesLocLabel() {
		var source = @"
            .org $8000
            jmp $8200
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("loc_8200"));
		Assert.Equal(0x8200, analyzer.SymbolTable.Symbols["loc_8200"].Value);
	}

	[Fact]
	public void AutoGenerateLabels_Disabled_DoesNotCreateLabels() {
		var source = @"
            .org $8000
            jsr $8100
            jmp $8200
        ";

		var analyzer = AnalyzeWithAutoLabels(source, enableAutoLabels: false);

		Assert.False(analyzer.SymbolTable.Symbols.ContainsKey("sub_8100"));
		Assert.False(analyzer.SymbolTable.Symbols.ContainsKey("loc_8200"));
	}

	[Fact]
	public void AutoGenerateLabels_ExistingLabel_DoesNotDuplicate() {
		var source = @"
            .org $8000
start:
            jsr my_routine
            rts

my_routine:
            nop
            rts
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		// Should not create sub_8004 because my_routine is defined
		// The address of my_routine depends on the code layout
		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("my_routine"));
		// No auto-generated labels should be created since we're calling a label
		Assert.DoesNotContain(analyzer.SymbolTable.Symbols.Values, s => s.Name.StartsWith("sub_"));
	}

	[Fact]
	public void AutoGenerateLabels_MultipleJsrSameTarget_OnlyOneLabelCreated() {
		var source = @"
            .org $8000
            jsr $8100
            jsr $8100
            jsr $8100
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		// Should only create one label for the address
		var subLabels = analyzer.SymbolTable.Symbols.Values
			.Count(s => s.Name == "sub_8100");
		Assert.Equal(1, subLabels);
	}

	[Fact]
	public void AutoGenerateLabels_ZeroPageAddress_CreatesLabel() {
		var source = @"
            .org $8000
            jsr $00
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("sub_0000"));
	}

	[Fact]
	public void AutoGenerateLabels_MixedJsrJmp_CreatesBothTypes() {
		var source = @"
            .org $8000
            jsr $8100
            jmp $8200
            jsr $8300
            jmp $8400
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("sub_8100"));
		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("loc_8200"));
		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("sub_8300"));
		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("loc_8400"));
	}

	[Fact]
	public void AutoGenerateLabels_IndirectJmp_DoesNotCreateLabel() {
		var source = @"
            .org $8000
            jmp ($8100)
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		// Indirect JMP shouldn't create auto-labels (the target is read from memory)
		Assert.False(analyzer.SymbolTable.Symbols.ContainsKey("loc_8100"));
	}

	[Fact]
	public void AutoGenerateLabels_BranchInstruction_DoesNotCreateLabel() {
		var source = @"
            .org $8000
            beq $8010
            bne $8020
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		// Branch instructions shouldn't create auto-labels (they use relative addressing)
		Assert.False(analyzer.SymbolTable.Symbols.ContainsKey("loc_8010"));
		Assert.False(analyzer.SymbolTable.Symbols.ContainsKey("loc_8020"));
	}

	[Fact]
	public void AutoGenerateLabels_LabelsAreInSymbolTable() {
		var source = @"
            .org $8000
            jsr $8100
            jmp $8200
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		// Verify they're proper Label symbols
		Assert.Equal(SymbolType.Label, analyzer.SymbolTable.Symbols["sub_8100"].Type);
		Assert.Equal(SymbolType.Label, analyzer.SymbolTable.Symbols["loc_8200"].Type);
		Assert.True(analyzer.SymbolTable.Symbols["sub_8100"].IsDefined);
		Assert.True(analyzer.SymbolTable.Symbols["loc_8200"].IsDefined);
	}

	[Fact]
	public void AutoGenerateLabels_LowercaseHexInName() {
		var source = @"
            .org $8000
            jsr $ABCD
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		// Verify label was created and the actual name uses lowercase hex
		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("sub_abcd"));
		// Verify the actual stored name is lowercase
		var symbol = analyzer.SymbolTable.Symbols["sub_abcd"];
		Assert.Equal("sub_abcd", symbol.Name);
	}

	[Fact]
	public void AutoGenerateLabels_ExpressionOperand_DoesNotCreateLabel() {
		var source = @"
            .org $8000
            BASE = $8000
            jsr BASE + $100
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		// Expressions aren't simple number literals, so no auto-label
		Assert.False(analyzer.SymbolTable.Symbols.ContainsKey("sub_8100"));
	}

	[Fact]
	public void AutoGenerateLabels_SymbolReference_DoesNotCreateLabel() {
		var source = @"
            .org $8000
            my_label = $8100
            jsr my_label
        ";

		var analyzer = AnalyzeWithAutoLabels(source);

		// Using a symbol reference shouldn't create an auto-label
		Assert.True(analyzer.SymbolTable.Symbols.ContainsKey("my_label"));
		Assert.False(analyzer.SymbolTable.Symbols.ContainsKey("sub_8100"));
	}
}

