// ============================================================================
// IncbinDirectiveTests.cs - Tests for .incbin directive
// Poppy Compiler - Multi-system Assembly Compiler
// ============================================================================

using Poppy.Core.CodeGen;
using Poppy.Core.Semantics;
using Xunit;

namespace Poppy.Tests.CodeGen;

/// <summary>
/// Tests for the .incbin directive supporting full file, offset, and length parameters.
/// </summary>
public class IncbinDirectiveTests {
	/// <summary>
	/// Helper to compile source and return generated bytes.
	/// </summary>
	private static (byte[] Code, CodeGenerator Generator, SemanticAnalyzer Analyzer) Compile(string source, string filename = "test.pasm") {
		var lexer = new Core.Lexer.Lexer(source, filename);
		var tokens = lexer.Tokenize();
		var parser = new Core.Parser.Parser(tokens);
		var program = parser.Parse();

		var analyzer = new SemanticAnalyzer(TargetArchitecture.MOS6502);
		analyzer.Analyze(program);

		var generator = new CodeGenerator(analyzer);
		var code = generator.Generate(program);

		return (code, generator, analyzer);
	}

	[Fact]
	public void Incbin_MissingFile_ReportsError() {
		var source = @"
.incbin ""nonexistent.bin""
";
		var (code, gen, analyzer) = Compile(source);

		Assert.True(gen.HasErrors);
		Assert.Contains(gen.Errors, e => e.Message.Contains("not found"));
	}

	[Fact]
	public void Incbin_MissingFilename_ReportsError() {
		var source = @"
.incbin
";
		var (code, gen, analyzer) = Compile(source);

		Assert.True(gen.HasErrors);
		Assert.Contains(gen.Errors, e => e.Message.Contains("Missing filename"));
	}

	// Note: Tests for actual file inclusion require a test file to be present.
	// The implementation supports:
	// - .incbin "file.bin"           ; Include entire file
	// - .incbin "file.bin", 16       ; Skip first 16 bytes
	// - .incbin "file.bin", 16, 256  ; Skip 16, include 256 bytes
	// 
	// The code in CodeGenerator.HandleIncbinDirective:
	// - Handles offset and length parameters
	// - Validates offset is within file bounds
	// - Validates offset + length doesn't exceed file size
}
